/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.property;

import com.cfg.PublicPropertyTmp;
import com.controller.XMLClientController;
import com.helper.file.FileHelper;
import java.io.File;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author xudong.weng
 */
public class JDInit extends javax.swing.JDialog {

    /**
     * Creates new form JDInit
     */
    public JDInit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getReadConfig();
        
    }
    
    private PublicPropertyTmp ppt=new PublicPropertyTmp();
    public void getReadConfig(){
        XMLClientController.readConfig("config", ppt);
        this.jtfMyIndex.setText(ppt.getMysqlIndex());
        this.jtfMyError.setText(ppt.getErr());
        this.jcbEncode.setSelectedItem(ppt.getEncoding());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbnOK = new javax.swing.JButton();
        jcbEncode = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMyError = new javax.swing.JTextField();
        jtfMyIndex = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("配置");
        setResizable(false);

        jbnOK.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbnOK.setText("确定");
        jbnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnOKActionPerformed(evt);
            }
        });

        jcbEncode.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jcbEncode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "utf8", "gbk", "gb2312" }));

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel4.setText("编码：");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel3.setText("错误记录：");

        jtfMyError.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jtfMyError.setText("myerr");

        jtfMyIndex.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jtfMyIndex.setText("mysqlindex");

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel1.setText("索引：");

        jbnCancel.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbnCancel.setText("取消");
        jbnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfMyError, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jcbEncode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfMyIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jbnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jbnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfMyIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMyError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbEncode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnOKActionPerformed
        if(this.jtfMyIndex.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "索引不能为空。", "错误", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(this.jtfMyError.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "错误不能为空。", "错误", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        PublicPropertyTmp ppt=new PublicPropertyTmp();
        ppt.setMysqlClientIndex(this.jtfMyIndex.getText());
        ppt.setErr(this.jtfMyError.getText());
        ppt.setEncoding(this.jcbEncode.getSelectedItem().toString());
        XMLClientController.updateConfig("config", ppt);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jbnOKActionPerformed

    private void jbnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbnCancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbnCancel;
    private javax.swing.JButton jbnOK;
    private javax.swing.JComboBox jcbEncode;
    private javax.swing.JTextField jtfMyError;
    private javax.swing.JTextField jtfMyIndex;
    // End of variables declaration//GEN-END:variables
}
