/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view.sub;


import javax.swing.JOptionPane;
import com.cfg.PublicProperty;
import com.controller.XMLClientController;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import com.model.IPPort;
import com.model.IPPortDic;
import com.model.MongoDic;



/**
 *
 * @author xudong.weng
 */
public final class JDCreateIPPort extends javax.swing.JDialog {

  
    public JDCreateIPPort(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setValue();
    }
    
    
    //初始化参数值
    private String ipportkey="";
    public String getIPPortkey(){
        return this.ipportkey;
    }
    
    public void setValue(){
        this.jtfServer.setText("localhost");
        this.jsRemotePort.setValue(13306);
        this.ipportkey="";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfServer = new javax.swing.JTextField();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jsRemotePort = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("新建连接");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel2.setText("服务器：");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel3.setText("端口：");

        jtfServer.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jbOK.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbOK.setText("确定");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbCancel.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbCancel.setText("取消");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jsRemotePort.setModel(new SpinnerNumberModel(1, 1, 65535, 1));
        jsRemotePort.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfServer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsRemotePort, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsRemotePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbOK, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        final JSpinner.NumberEditor editorport=new JSpinner.NumberEditor(jsRemotePort,"0");
        jsRemotePort.setEditor(editorport);
        final JFormattedTextField textFieldport = ((JSpinner.NumberEditor)jsRemotePort.getEditor()).getTextField();
        textFieldport.setEditable(true);
        // 开启输入的值的限制
        final DefaultFormatterFactory factoryport = (DefaultFormatterFactory)textFieldport.getFormatterFactory();
        final NumberFormatter formatterport = (NumberFormatter)factoryport.getDefaultFormatter();
        formatterport.setAllowsInvalid(false);// 此处对输入的有效性进行控制。若改为true，则不控制有效性

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.ipportkey="";
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed

        if(IPPortDic.getIPPort(this.jtfServer.getText()+"_"+this.jsRemotePort.getValue().toString())==null){
            
            XMLClientController.addIPPort(this.jtfServer.getText(),this.jsRemotePort.getValue().toString(),PublicProperty.getMysqlClientIndex());//在xml中添加
            this.ipportkey=this.jtfServer.getText()+"_"+this.jsRemotePort.getValue().toString();
            IPPortDic.setIPPort(new IPPort(this.jtfServer.getText(),this.jsRemotePort.getValue().toString()));
            MongoDic.setMongo(new IPPort(this.jtfServer.getText(),this.jsRemotePort.getValue().toString()), null);
            this.dispose();
        }else{
            IPPortDic.printIPPorts();
            //JOptionPane.showMessageDialog(null, URLDic.getURL(this.jtfLinkName.getText()), "错误", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "连接名已经存在", "错误", JOptionPane.ERROR_MESSAGE);
        }
  
    }//GEN-LAST:event_jbOKActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JSpinner jsRemotePort;
    private javax.swing.JTextField jtfServer;
    // End of variables declaration//GEN-END:variables

}
