/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xml.view.sub;

import com.xml.controller.XMLController;
import com.xml.helper.MySQLHelper;
import javax.swing.JOptionPane;
import com.xml.cfg.PublicProperty;
import com.xml.model.url.URL;
import com.xml.model.url.URLDic;


/**
 *
 * @author xudong.weng
 */
public final class JDCreateURL extends javax.swing.JDialog {

  
    public JDCreateURL(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setValue();
    }
    
    
    //初始化参数值
    private String linkname="";
    public String getLinkname(){
        return this.linkname;
    }
    
    public void setValue(){
        this.jtfLinkName.setText("");
        this.jtfSavePath.setText("");
        this.jtfServer.setText("localhost");
        this.jtfPort.setText("3306");
        this.jtfUser.setText("root");
        this.jpfPassword.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfLinkName = new javax.swing.JTextField();
        jtfServer = new javax.swing.JTextField();
        jtfPort = new javax.swing.JTextField();
        jtfUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbTest = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jpfPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jtfSavePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("新建连接");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel1.setText("连接名：");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel2.setText("服务器：");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel3.setText("端口：");

        jtfLinkName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jtfServer.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jtfPort.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jtfUser.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel4.setText("用户名：");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel5.setText("密码：");

        jbTest.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbTest.setText("测试");
        jbTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTestActionPerformed(evt);
            }
        });

        jbOK.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbOK.setText("确定");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbCancel.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbCancel.setText("取消");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jpfPassword.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel6.setText("备份路径：");

        jtfSavePath.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbTest, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLinkName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfServer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(jpfPassword)
                                .addComponent(jtfSavePath)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfLinkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTestActionPerformed
        
        if(MySQLHelper.getCon(this.jtfUser.getText(), String.valueOf(this.jpfPassword.getPassword()), this.jtfServer.getText(),this.jtfPort.getText())==1){
            JOptionPane.showMessageDialog(null, "连接成功", "测试", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "连接失败", "测试", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbTestActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.linkname="";
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        if(!this.jtfLinkName.getText().equals("")){
            if(URLDic.getURL(this.jtfLinkName.getText())==null){
                PublicProperty.setBakid(PublicProperty.getBakid()+1);//增加最大备份顺序号
                URL url=new URL(this.jtfUser.getText(), String.valueOf(this.jpfPassword.getPassword()),this.jtfServer.getText(),this.jtfPort.getText(),this.jtfSavePath.getText(),String.valueOf(PublicProperty.getBakid()));
                XMLController.addURL(this.jtfLinkName.getText(),url,PublicProperty.getMysqlIndex());//在xml中添加
                this.linkname=this.jtfLinkName.getText();
                URLDic.setURL(this.linkname, url);//添加URL
                this.dispose();
            }else{
                URLDic.printURLs();
                //JOptionPane.showMessageDialog(null, URLDic.getURL(this.jtfLinkName.getText()), "错误", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(null, "连接名已经存在", "错误", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "连接名不能为空", "错误", JOptionPane.ERROR_MESSAGE);
            this.jtfLinkName.requestFocus();
        }
    }//GEN-LAST:event_jbOKActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JButton jbTest;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfLinkName;
    private javax.swing.JTextField jtfPort;
    private javax.swing.JTextField jtfSavePath;
    private javax.swing.JTextField jtfServer;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables

}
