/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mongodb.view.sub;


import com.mongodb.controller.MongoDBController;
import com.xml.helper.MySQLHelper;
import javax.swing.JOptionPane;
import com.xml.model.url.URL;
import com.xml.model.url.URLDic;
import com.xml.model.url.link.DatabaseDic;
import com.xml.model.url.link.LinkDic;


/**
 *
 * @author xudong.weng
 */
public final class JDEditURLs extends javax.swing.JDialog {

    
    public JDEditURLs(java.awt.Frame parent, boolean modal,String linkname) {
        super(parent, modal);
        initComponents();
        URL url=URLDic.getURL(linkname);
        this.jtfLinkName.setText(linkname);
        this.jtfSavePath.setText(url.getSavepath());
        this.jtfServer.setText(url.getServer());
        this.jtfPort.setText(url.getPort());
        this.jtfUser.setText(url.getUser());
        this.jpfPassword.setText(url.getPwd());
        this.linkname=linkname;
    }
    
    //初始化参数值
    private String linkname="";
    public String getLinkname(){
        return this.linkname;
    }
    public void setLinkname(String linkname){
        this.linkname=linkname;
    }
    
    public void setvalue(String linkname){
        URL url=URLDic.getURL(linkname);
        this.jtfLinkName.setText(linkname);
        this.jtfSavePath.setText(url.getSavepath());
        this.jtfServer.setText(url.getServer());
        this.jtfPort.setText(url.getPort());
        this.jtfUser.setText(url.getUser());
        this.jpfPassword.setText(url.getPwd());
        this.linkname=linkname;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfLinkName = new javax.swing.JTextField();
        jtfServer = new javax.swing.JTextField();
        jtfPort = new javax.swing.JTextField();
        jtfUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbTest = new javax.swing.JButton();
        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jpfPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jtfSavePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Link");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel1.setText("Link：");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel2.setText("Server：");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel3.setText("Port：");

        jtfLinkName.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jtfServer.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jtfPort.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jtfUser.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel4.setText("User：");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel5.setText("Password：");

        jbTest.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbTest.setText("Test");
        jbTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTestActionPerformed(evt);
            }
        });

        jbOK.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jbCancel.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jpfPassword.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        jLabel6.setText("Path：");

        jtfSavePath.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbTest, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLinkName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfServer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfUser)
                                .addComponent(jpfPassword)
                                .addComponent(jtfSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfLinkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTestActionPerformed
      
        if(MySQLHelper.getCon(this.jtfUser.getText(), String.valueOf(this.jpfPassword.getPassword()), this.jtfServer.getText(),this.jtfPort.getText())==1){
            JOptionPane.showMessageDialog(null, "Connection is success", "Test", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Connection is failture", "Test", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbTestActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.linkname="";
        this.dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        if(!this.jtfLinkName.getText().equals("")){
            //判断新linkname是否与原linkname相同，如不相同，则判断是否与其他linkname是否相同。
            if((!this.jtfLinkName.getText().equals(this.linkname)&&URLDic.getURL(this.jtfLinkName.getText())==null)||
                    this.jtfLinkName.getText().equals(this.linkname)
                    ){
                DatabaseDic dd=LinkDic.getLink(this.linkname);
                
                if(dd==null){
                    dd=new DatabaseDic();
                }
                DatabaseDic ddcp=dd.cloneDic();
                dd.clearAll();
                LinkDic.removeLink(this.linkname);
                LinkDic.setLink(this.jtfLinkName.getText(), ddcp);
                //新建URL对象
                URL url=new URL(this.jtfUser.getText(), String.valueOf(this.jpfPassword.getPassword()),this.jtfServer.getText(),this.jtfPort.getText(),this.jtfSavePath.getText(),URLDic.getURL(linkname).getBakid());

                
                if(MongoDBController.updateLinkname(linkname, this.jtfLinkName.getText(), url)==-1){
                    JOptionPane.showMessageDialog(null, "Update is error", "Error", JOptionPane.ERROR_MESSAGE);
                }
                URLDic.removeURL(linkname);//删除原URL
                this.linkname=this.jtfLinkName.getText();
                URLDic.setURL(linkname, url);//新增新URL
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Link is not exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Link is invaild", "Error", JOptionPane.ERROR_MESSAGE);
            this.jtfLinkName.requestFocus();
        }
    }//GEN-LAST:event_jbOKActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JButton jbTest;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfLinkName;
    private javax.swing.JTextField jtfPort;
    private javax.swing.JTextField jtfSavePath;
    private javax.swing.JTextField jtfServer;
    private javax.swing.JTextField jtfUser;
    // End of variables declaration//GEN-END:variables

}
